// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT9XG7XvOvkN5z9k1LBYraXu2eox37U8s',
    appId: '1:644489970165:web:a0ab6631bfe50e9a0be0bc',
    messagingSenderId: '644489970165',
    projectId: 'mealify-connect',
    authDomain: 'mealify-connect.firebaseapp.com',
    storageBucket: 'mealify-connect.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfsXsCBAeHedERbtaCaW-9xHN-Q-XUkVQ',
    appId: '1:644489970165:android:c91edf5179c1d89b0be0bc',
    messagingSenderId: '644489970165',
    projectId: 'mealify-connect',
    storageBucket: 'mealify-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNtA_u8zb5dET8lp5SqqB-44vz8Q1cE8A',
    appId: '1:644489970165:ios:84c3e6f59965cd310be0bc',
    messagingSenderId: '644489970165',
    projectId: 'mealify-connect',
    storageBucket: 'mealify-connect.appspot.com',
    iosBundleId: 'com.example.mealifyProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNtA_u8zb5dET8lp5SqqB-44vz8Q1cE8A',
    appId: '1:644489970165:ios:9f267ce88c9aefa20be0bc',
    messagingSenderId: '644489970165',
    projectId: 'mealify-connect',
    storageBucket: 'mealify-connect.appspot.com',
    iosBundleId: 'com.example.mealifyProvider.RunnerTests',
  );
}
